### ISSUE TITLE
Add encryption and job signing for multi-user queues

### ISSUE THREAD

**Issue by peterfoley** [PieceMaker/rminions#9]
Use case I have in mind is for a shared cluster of multi-user Linux worker nodes that can run jobs as specific users. Since Redis itself has minimal authentication, and R tasks can run arbitrary code, it would be useful for the submitters to be able to submit jobs that:
- are encrypted using a key accessible only to that user
- are signed by that user

and then workers will need to:
- determine which user a job should run as
- verify the job has been signed by that user
- encrypt the actual contents of the job
- run the job as the user (preferably in an R session started as the user, with their config/environment/libraries)

The users in our environment already have ssh public/private keys that could likely be repurposed for this using existing functionality from the [openssl package](https://cran.r-project.org/web/packages/openssl/index.html)

**Comment by PieceMaker** [comment]
Right now the goal of the minion workers is that they are "dumb." They accept whatever is passed to them and process it as quickly as possible so they can move to the next job and continue until there are no more jobs left. The current design is based on the assumption that any user that can access the workers (and the jobs they send) is trusted and this access is controlled by network rules allowing or blocking access to the server running the workers. This way bypasses the need for the workers to maintain a collection of keys for encryption/decryption and allows them to focus on processing.

Extending this, if the minions were to determine which user to execute a job as and use a pre-specified environment, then this would require some form of database which quickly exceeds the scope of what this package is trying to accomplish. Additionally, of the aforementioned config, environment, and libraries, libraries are the only ones that I would expect to be significant as config and environment could be specified as arguments to functions defined in custom libraries. For this, the `Packages` key of the `params` list could be used to preload any custom libraries and then functions from these libraries could be called with the appropriate environment and config definitions.

Finally, I understand that it would be good practice to encrypt the jobs whenever using workers on remote servers such as EC2. Rather than encrypting and decrypting messages with R, I would suggest using the Redis recommended encryption method: http://redis.io/topics/encryption.
